### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by gallart** [antongunov/favicongrabber.com#14]
Hi,

i'm trying to build the project with yarn, but no lock so far :

```
# node -v
v6.14.1

```

```
yarn install v1.6.0
info No lockfile found.
[1/4] Resolving packages...
warning browser-sync > socket.io > engine.io > uws@9.14.0: stop using this version
warning gulp-pug > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-sass > gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
warning jest > jest-cli > istanbul-api > istanbul-lib-hook@1.2.1: 1.2.0 should have been a major version bump
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
warning Your current version of Yarn is out of date. The latest version is "1.7.0", while you're on "1.6.0".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
$ run-s build version nginx
yarn run v1.6.0
$ npm run clean && run-p build:*

> favicongrabber.com@0.1.0 clean /var/www/localhost/htdocs/favicongrabber.com
> rm -rf build

$ gulp default:production
$ webpack --progress --hide-modules
/var/www/localhost/htdocs/favicongrabber.com/webpack.config.js:23
  );
  ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at requireConfig (/var/www/localhost/htdocs/favicongrabber.com/node_modules/webpack/bin/convert-argv.js:97:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with signal "SIGTERM".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build:webpack" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "build" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

Do you have some doc/requirements somewhere ?

Thanks

**Comment by gallart** [comment]
Actually, yarn is useless. : `npm install` is enough :)
